type LifeCycleName =
  | 'onLoad'
  | 'onShow'
  | 'onReady'
  | 'onHide'
  | 'onTitleClick'
  | 'onPullDownRefresh'
  | 'onReachBottom'
  | 'onShareAppMessage'
  | 'onUnload'
  | 'onInit'
  | 'deriveDataFromProps'
  | 'didMount'
  | 'didUpdate'
  | 'didUnmount'
